kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  name: report-server
  namespace: nlilaramani-dev
  labels:
    app: report-server
spec:
  selector:
    matchLabels:
      app: report-server
  template:
    metadata:
      labels:
        app: report-server
    spec:
      containers:
        - name: report-server
          image: nginx
          ports:
            - containerPort: 80
              protocol: "TCP"
          volumeMounts:
            - mountPath: /data
              name: report-data
            restartPolicy: Always
            volumes:
              - name: remote-data
                persistentVolumeClaim:
                  claimName: shared-data
  replicas: 1
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 2
  minReadySeconds: 0